"""Docker-oriented hosting provider protocol (Fase 4 live surface).

Implemented by DockerHostingProvider (app.modules.hosting.provider).
Hestia account-style ops live separately in hestia.py (legacy concept).
"""

from typing import Protocol, runtime_checkable


@runtime_checkable
class DockerHostingProviderProtocol(Protocol):
    """status/metrics/logs/restart/files/backups — Innexar Cloud surface."""

    def status(self, name: str) -> object: ...
    def metrics(self, name: str) -> dict: ...
    def logs(self, name: str, tail: int = 200) -> str: ...
    def restart(self, name: str, timeout: int = 90) -> None: ...
    def start(self, name: str) -> None: ...
    def stop(self, name: str, timeout: int = 60) -> None: ...
    def list_files(self, container: str, base: str, rel: str) -> list: ...
    def read_file(self, container: str, base: str, rel: str) -> bytes: ...
    def write_file(self, container: str, base: str, rel: str, data: bytes) -> None: ...
