"""add requires_password_change flag

Revision ID: c7079727f866
Revises: h5c6d7e8f9a0
Create Date: 2026-03-07 19:23:23.723360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7079727f866'
down_revision: Union[str, None] = 'h5c6d7e8f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_users', sa.Column('requires_password_change', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_users', 'requires_password_change')
    # ### end Alembic commands ###
